# Generated by Django 6.0.4 on 2026-04-13 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('train_type', models.CharField(choices=[('RAJ', 'Rajdhani'), ('SHT', 'Shatabdi'), ('DUR', 'Duronto'), ('EXP', 'Express'), ('MAIL', 'Mail'), ('PAS', 'Passenger'), ('SF', 'Superfast'), ('ICE', 'InterCity Express')], max_length=10)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('distance_km', models.IntegerField(default=0)),
                ('runs_on_mon', models.BooleanField(default=True)),
                ('runs_on_tue', models.BooleanField(default=True)),
                ('runs_on_wed', models.BooleanField(default=True)),
                ('runs_on_thu', models.BooleanField(default=True)),
                ('runs_on_fri', models.BooleanField(default=True)),
                ('runs_on_sat', models.BooleanField(default=True)),
                ('runs_on_sun', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pantry_car', models.BooleanField(default=False)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_trains', to='trains.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_trains', to='trains.station')),
            ],
        ),
        migrations.CreateModel(
            name='CoachClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_class', models.CharField(choices=[('1A', 'First AC'), ('2A', 'Second AC'), ('3A', 'Third AC'), ('SL', 'Sleeper'), ('CC', 'Chair Car'), ('2S', 'Second Sitting'), ('GN', 'General'), ('FC', 'First Class')], max_length=5)),
                ('total_seats', models.IntegerField()),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tatkal_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('coach_count', models.IntegerField(default=1)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_classes', to='trains.train')),
            ],
            options={
                'unique_together': {('train', 'coach_class')},
            },
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('available_seats', models.IntegerField()),
                ('waitlist_count', models.IntegerField(default=0)),
                ('rac_count', models.IntegerField(default=0)),
                ('coach_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='trains.coachclass')),
            ],
            options={
                'unique_together': {('coach_class', 'journey_date')},
            },
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('distance_from_source', models.IntegerField(default=0)),
                ('halt_minutes', models.IntegerField(default=2)),
                ('platform_number', models.IntegerField(default=1)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trains.train')),
            ],
            options={
                'ordering': ['stop_number'],
                'unique_together': {('train', 'stop_number')},
            },
        ),
    ]
