# Generated by Django 6.0.4 on 2026-04-14 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HERITAGE', 'Heritage'), ('PILGRIMAGE', 'Pilgrimage'), ('HILL_STATION', 'Hill Station'), ('BEACH', 'Beach'), ('WILDLIFE', 'Wildlife'), ('SPECIAL', 'Special')], max_length=20)),
                ('description', models.TextField()),
                ('itinerary', models.TextField()),
                ('duration_nights', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('price_per_person', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inclusions', models.TextField()),
                ('source_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('max_group_size', models.IntegerField(default=20)),
                ('is_active', models.BooleanField(default=True)),
                ('image_emoji', models.CharField(default='🏔️', max_length=10)),
                ('highlights', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=10)),
                ('delivery_date', models.DateField()),
                ('coach_number', models.CharField(max_length=5)),
                ('seat_number', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('PLACED', 'Order Placed'), ('CONFIRMED', 'Confirmed'), ('PREPARING', 'Preparing'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PLACED', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_id', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CateringVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=4.0, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('min_order', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('delivery_time_minutes', models.IntegerField(default=30)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='trains.station')),
            ],
        ),
        migrations.CreateModel(
            name='LiveTrainStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('delay_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ON_TIME', 'Running On Time'), ('DELAYED', 'Delayed'), ('CANCELLED', 'Cancelled'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed')], default='ON_TIME', max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('speed_kmph', models.IntegerField(default=0)),
                ('current_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_statuses', to='trains.train')),
            ],
            options={
                'unique_together': {('train', 'journey_date')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('MEAL', 'Full Meal'), ('SNACK', 'Snacks'), ('BEVERAGE', 'Beverages'), ('BREAKFAST', 'Breakfast'), ('DESSERT', 'Desserts'), ('COMBO', 'Combo')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_veg', models.BooleanField(default=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_emoji', models.CharField(default='🍱', max_length=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='services.cateringvendor')),
            ],
        ),
        migrations.CreateModel(
            name='CateringOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.cateringorder')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly')], max_length=15)),
                ('travel_class', models.CharField(choices=[('2S', 'Second Sitting'), ('SL', 'Sleeper'), ('3A', 'Third AC'), ('2A', 'Second AC'), ('CC', 'Chair Car')], max_length=5)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pass_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_to', to='trains.station')),
                ('source_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes_from', to='trains.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_passes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainStopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField()),
                ('scheduled_arrival', models.TimeField(blank=True, null=True)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('actual_arrival', models.TimeField(blank=True, null=True)),
                ('actual_departure', models.TimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DEPARTED', 'Departed'), ('AT_STATION', 'At Station'), ('UPCOMING', 'Upcoming'), ('SKIPPED', 'Skipped')], default='UPCOMING', max_length=20)),
                ('platform_number', models.IntegerField(default=1)),
                ('live_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_statuses', to='services.livetrainstatus')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.station')),
            ],
            options={
                'ordering': ['stop_number'],
            },
        ),
        migrations.CreateModel(
            name='TrainAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('pnr', models.CharField(blank=True, max_length=10)),
                ('alert_type', models.CharField(choices=[('DELAY', 'Train Delay'), ('PLATFORM', 'Platform Change'), ('CANCELLATION', 'Train Cancellation'), ('CHART', 'Chart Preparation'), ('PNR', 'PNR Status Change')], max_length=20)),
                ('via_sms', models.BooleanField(default=True)),
                ('via_email', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'train', 'journey_date', 'alert_type')},
            },
        ),
    ]
