# Generated by Django 6.0.4 on 2026-04-13 09:26

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('berth_preference', models.CharField(choices=[('LB', 'Lower'), ('MB', 'Middle'), ('UB', 'Upper'), ('SL', 'Side Lower'), ('SU', 'Side Upper'), ('NP', 'No Preference')], default='NP', max_length=5)),
                ('berth_allotted', models.CharField(blank=True, max_length=5)),
                ('coach_number', models.CharField(blank=True, max_length=5)),
                ('seat_number', models.CharField(blank=True, max_length=5)),
                ('status', models.CharField(choices=[('CNF', 'Confirmed'), ('WL', 'Waitlisted'), ('RAC', 'RAC'), ('CAN', 'Cancelled')], default='CNF', max_length=10)),
                ('waitlist_number', models.IntegerField(blank=True, null=True)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=50)),
                ('is_senior_citizen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(default=bookings.models.generate_pnr, max_length=10, unique=True)),
                ('journey_date', models.DateField()),
                ('status', models.CharField(choices=[('CNF', 'Confirmed'), ('WL', 'Waitlisted'), ('RAC', 'RAC'), ('CAN', 'Cancelled'), ('PCAN', 'Partially Cancelled')], default='CNF', max_length=10)),
                ('quota', models.CharField(choices=[('GN', 'General'), ('TK', 'Tatkal'), ('PT', 'Premium Tatkal'), ('LD', 'Ladies'), ('HH', 'Physically Handicapped'), ('DF', 'Defence')], default='GN', max_length=5)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('chart_prepared', models.BooleanField(default=False)),
                ('boarding_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarding_bookings', to='trains.station')),
                ('coach_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.coachclass')),
                ('destination_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_bookings', to='trains.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.train')),
            ],
        ),
    ]
